name: Build

on: push

jobs:
  build: # job 의 이름
    runs-on: ubuntu-latest # 실행할 OS 환경
    steps: # job 을 실행할 단계
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
